### ISSUE TITLE
All bmsforum.org links are bad because bmsforum.org no longer exists. 

### ISSUE THREAD

**Issue by royobrecht** [redterror/f4bms-dedicated-server#1]
All bmsforum.org links are bad because bmsforum.org no longer exists. 

![screenshot from 2018-11-24 22-44-56](https://user-images.githubusercontent.com/7474477/48976358-d6f5c300-f03a-11e8-8c03-7a58461568b3.png)

**Comment by redterror** [comment]
Links updated, thanks.
